version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=spring-test
    - MYSQL_PASSWORD=spring-test
    - MYSQL_DATABASE=spring-test
    ports:
    - 3306:3306